name: CI+CD Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  ci:
    runs-on: ubuntu-latest

    # ðŸ‘‡ definimos las credenciales Parse UNA sola vez
    env:
      NODE_ENV: test
      PARSE_APP_ID: palasaca-local-app
      PARSE_MASTER_KEY: palasaca-local-master
      PARSE_SERVER_URL: http://parse:1337/parse

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

      parse:
        image: parseplatform/parse-server
        ports:
          - 1337:1337
        env:
          PARSE_SERVER_APPLICATION_ID: palasaca-local-app
          PARSE_SERVER_MASTER_KEY: palasaca-local-master
          PARSE_SERVER_DATABASE_URI: mongodb://mongo:27017/palasaca_test
          PARSE_SERVER_URL: http://localhost:1337/parse

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run tests
        env:
          # ðŸ‘‡ inyectamos estos envs al proceso de Node tambiÃ©n
          APP_ID_DEV: ${{ env.PARSE_APP_ID }}
          MASTER_KEY_DEV: ${{ env.PARSE_MASTER_KEY }}
          PARSE_SERVER_URL: ${{ env.PARSE_SERVER_URL }}
          NODE_ENV: test
        run: npm test
